//
//  print_usage.h
//  BAM_QC
//
//  Created by Pelin Sahlen on 12/08/2015.
//  Copyright (c) 2015 Pelin Sahlen. All rights reserved.
//

static int print_usage()
{
    fprintf(stderr, "\n");
    fprintf(stderr, "Program: BAMStats \n");
    fprintf(stderr, "Contact: Pelin Sahlén <pelin.akan@scilifelab.se>\n\n");
    fprintf(stderr, "Usage:   BAMStats bamfile \n");
    fprintf(stderr, "This program prints out read and insert size statistics, coverage and complexity \n");
    fprintf(stderr, "histograms (generated by lc_extrap --quick mode) of the bam file given \n");
    
    return 0;
}
